name: PMD

on: [pull_request]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2 # v2 minimum required
      
      - name: gradlew change mode
        run: chmod +x gradlew

      - name: create table on database
        run: ./gradlew pmdMain